name: Ec2 deploy
on:
  push:
    branches: [ master ]

jobs:
  EC2-Deploy:
    runs-on: ubuntu-latest
    environment: 
      name: aws
    
    steps:
    - uses: actions/checkout@v3
    - name: Compile 
      run: mvn clean package
    - name: show path
      run: echo ${{vars.GITHUB_WORKSPACE}}
    - name: War Generated  
      run: ls $GITHUB_WORKSPACE/target/  
      
    - id: deploy
      uses: bitovi/github-actions-deploy-docker-to-ec2@v1.0.0
      with:
        aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
        aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        aws_default_region: us-east-1
        docker_repo_app_directory: ${{vars.GITHUB_WORKSPACE}}
        aws_elb_app_port: 8080 
    
